### PR TITLE
Update SPIPhysical.scala so channel 0 is sampled in single SPI mode

### PR DESCRIPTION
**Pull request by Kevin99214**
Changed from channel 1 being sampled for single SPI mode

### CODE REVIEW

**Comment by jerryz123** [comment]
Can you describe what this PR does a bit more? Is it fixing a bug? Or improving the behavior?

**Comment by Kevin99214** [comment]
It's a bit of both.

A QSPI model I'm using currently, when set to single SPI mode, responds on channel 0. This then is not being sampled by the device and my SPI reads always return 0.

But intuitively, different modes of SPI samples different amounts of rx input bits. 
- Quad SPI samples all rx bits ([3:0])
- Dual SPI samples lower 2 indexed rx bits([1:0])
The next step for Single SPI should be to sample only the lowest index ([0:0]) but it currently samples [1:1]

**Comment by jerryz123** [comment]
Ok, this change makes sense to me. can you sign the CLA?

**Comment by Kevin99214** [comment]
Ok signed. Thanks

**Comment by T-K-233** [comment]
> But intuitively, different modes of SPI samples different amounts of rx input bits.
> 
> * Quad SPI samples all rx bits ([3:0])
> * Dual SPI samples lower 2 indexed rx bits([1:0])
>   The next step for Single SPI should be to sample only the lowest index ([0:0]) but it currently samples [1:1]

I don't think this pattern is correct for single SPI mode.

Different from Dual and Quad SPI mode, Single SPI mode operates in full-duplex. So there are two pins, MOSI (Master Out Slave In) and MISO (Master In Slave Out).

The convention here is that MOSI gets mapped to pin(0), and MISO mapped to pin(1). Therefore, on receiving in Single SPI mode, it is correct to receive from `rxd_fin(1)`.

Please check if the QSPI model you are using also follows this convention. Could you provide a link to the device you are using?

Thanks.

**Comment by Kevin99214** [comment]
Ah sorry about that, I just checked the spec again. It does say that pin1 should be the response data pin. 

https://media-www.micron.com/-/media/client/global/documents/products/data-sheet/nor-flash/serial-nor/mt25q/die-rev-a/mt25q_qljs_u_256_aba_0.pdf?rev=59de7fdc073c47fd81ff0533f44733ef

Please feel free to revert this change. Thanks

**Pull request merged**
